env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

task:
  compute_engine_instance:
    image_project: freebsd-org-cloud-dev
    platform: freebsd
  matrix:
    - name: freebsd14-amd64
      freebsd_instance:
         image_family: freebsd-14-0-snap
    - name: freebsd13-amd64
      freebsd_instance:
         image: freebsd-13-0-release-amd64
    - name: freebsd12-amd64
      freebsd_instance:
         image: freebsd-12-3-release-amd64
  script:
    - make
